# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ravengui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(404, 300)
        Dialog.setStyleSheet("QDialog {\n"
"background-color: black;\n"
"color: white;\n"
"font-size: 14px;\n"
"}")
        self.logo = QtWidgets.QGraphicsView(Dialog)
        self.logo.setGeometry(QtCore.QRect(20, 20, 75, 75))
        self.logo.setStyleSheet("background-color: transparent; border: 0;")
        self.logo.setObjectName("logo")
        self.price_usd = QtWidgets.QLabel(Dialog)
        self.price_usd.setGeometry(QtCore.QRect(219, 28, 121, 31))
        self.price_usd.setStyleSheet("color: white; font-size: 22px;")
        self.price_usd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.price_usd.setObjectName("price_usd")
        self.usd_label = QtWidgets.QLabel(Dialog)
        self.usd_label.setGeometry(QtCore.QRect(348, 33, 51, 21))
        self.usd_label.setStyleSheet("color: white;")
        self.usd_label.setObjectName("usd_label")
        self.price_label = QtWidgets.QLabel(Dialog)
        self.price_label.setGeometry(QtCore.QRect(181, 33, 41, 31))
        self.price_label.setStyleSheet("color: white; font-size: 16px; color: orange;")
        self.price_label.setAlignment(QtCore.Qt.AlignCenter)
        self.price_label.setObjectName("price_label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(160, 19, 221, 81))
        self.frame.setStyleSheet("border: 2px solid white; border-radius: 15px; background-color: rgb(40,40,40);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.rank_number = QtWidgets.QLabel(Dialog)
        self.rank_number.setGeometry(QtCore.QRect(10, 250, 51, 41))
        self.rank_number.setStyleSheet("border: 1px solid white; border-radius: 15px; background-color: green; color: white; font-size: 22px;")
        self.rank_number.setAlignment(QtCore.Qt.AlignCenter)
        self.rank_number.setObjectName("rank_number")
        self.rank_label = QtWidgets.QLabel(Dialog)
        self.rank_label.setGeometry(QtCore.QRect(9, 221, 61, 21))
        self.rank_label.setStyleSheet("color: orange; font-size: 12px;")
        self.rank_label.setObjectName("rank_label")
        self.btc_label = QtWidgets.QLabel(Dialog)
        self.btc_label.setGeometry(QtCore.QRect(348, 70, 51, 21))
        self.btc_label.setStyleSheet("color: white;")
        self.btc_label.setObjectName("btc_label")
        self.price_btc = QtWidgets.QLabel(Dialog)
        self.price_btc.setGeometry(QtCore.QRect(218, 63, 121, 31))
        self.price_btc.setStyleSheet("color: white; font-size: 19px;")
        self.price_btc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.price_btc.setObjectName("price_btc")
        self.supply_percent = QtWidgets.QProgressBar(Dialog)
        self.supply_percent.setGeometry(QtCore.QRect(109, 265, 281, 16))
        self.supply_percent.setStyleSheet("color: white; font-size: 12px")
        self.supply_percent.setMaximum(2100000000)
        self.supply_percent.setProperty("value", 209191000)
        self.supply_percent.setTextVisible(True)
        self.supply_percent.setOrientation(QtCore.Qt.Horizontal)
        self.supply_percent.setInvertedAppearance(False)
        self.supply_percent.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.supply_percent.setObjectName("supply_percent")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(122, 241, 111, 16))
        self.label.setStyleSheet("color: orange; font-size: 13px;")
        self.label.setObjectName("label")
        self.supply_amount = QtWidgets.QLabel(Dialog)
        self.supply_amount.setGeometry(QtCore.QRect(230, 239, 100, 20))
        self.supply_amount.setStyleSheet("color: white; font-size: 12px;")
        self.supply_amount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.supply_amount.setObjectName("supply_amount")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(86, 125, 81, 21))
        self.label_2.setStyleSheet("color: orange; font-size: 15px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(262, 125, 81, 21))
        self.label_3.setStyleSheet("color: orange; font-size: 15px;")
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(36, 114, 331, 91))
        self.frame_2.setStyleSheet("border: 1px solid grey; border-radius: 15px; background-color: rgb(40,40,40);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.volume = QtWidgets.QLabel(Dialog)
        self.volume.setGeometry(QtCore.QRect(205, 146, 141, 31))
        self.volume.setStyleSheet("color: white; font-size: 22px;")
        self.volume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.volume.setObjectName("volume")
        self.market_cap = QtWidgets.QLabel(Dialog)
        self.market_cap.setGeometry(QtCore.QRect(47, 146, 141, 31))
        self.market_cap.setStyleSheet("color: white; font-size: 22px;")
        self.market_cap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.market_cap.setObjectName("market_cap")
        self.perc_change = QtWidgets.QLabel(Dialog)
        self.perc_change.setGeometry(QtCore.QRect(170, 53, 64, 31))
        self.perc_change.setStyleSheet("color: white; font-size: 15px;")
        self.perc_change.setAlignment(QtCore.Qt.AlignCenter)
        self.perc_change.setObjectName("perc_change")
        self.market_btc = QtWidgets.QLabel(Dialog)
        self.market_btc.setGeometry(QtCore.QRect(81, 180, 85, 16))
        self.market_btc.setStyleSheet("color: white; font-size: 12px;")
        self.market_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.market_btc.setObjectName("market_btc")
        self.volume_btc = QtWidgets.QLabel(Dialog)
        self.volume_btc.setGeometry(QtCore.QRect(245, 180, 84, 16))
        self.volume_btc.setStyleSheet("color: white; font-size: 12px;")
        self.volume_btc.setAlignment(QtCore.Qt.AlignCenter)
        self.volume_btc.setObjectName("volume_btc")
        self.frame_2.raise_()
        self.frame.raise_()
        self.logo.raise_()
        self.price_usd.raise_()
        self.usd_label.raise_()
        self.price_label.raise_()
        self.rank_number.raise_()
        self.rank_label.raise_()
        self.btc_label.raise_()
        self.price_btc.raise_()
        self.supply_percent.raise_()
        self.label.raise_()
        self.supply_amount.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.volume.raise_()
        self.market_cap.raise_()
        self.perc_change.raise_()
        self.market_btc.raise_()
        self.volume_btc.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.price_usd.setText(_translate("Dialog", "0.123456"))
        self.usd_label.setText(_translate("Dialog", "USD"))
        self.price_label.setText(_translate("Dialog", "Price"))
        self.rank_number.setText(_translate("Dialog", "1"))
        self.rank_label.setText(_translate("Dialog", "CMC Rank"))
        self.btc_label.setText(_translate("Dialog", "BTC"))
        self.price_btc.setText(_translate("Dialog", "0.123456"))
        self.supply_percent.setFormat(_translate("Dialog", "%p%"))
        self.label.setText(_translate("Dialog", "Circulating Supply: "))
        self.supply_amount.setText(_translate("Dialog", "2,091,910,000"))
        self.label_2.setText(_translate("Dialog", "Market Cap"))
        self.label_3.setText(_translate("Dialog", "Volume"))
        self.volume.setText(_translate("Dialog", "$81,005,687"))
        self.market_cap.setText(_translate("Dialog", "$112,284,337"))
        self.perc_change.setText(_translate("Dialog", "123.44%"))
        self.market_btc.setText(_translate("Dialog", "17,932 BTC"))
        self.volume_btc.setText(_translate("Dialog", "13,659 BTC"))

